### ISSUE TITLE
ROCm 4.1 - Vega 20 (Radeon VII) with upstream amdgpu

### ISSUE THREAD

**Issue by FilipVaverka** [RadeonOpenCompute/ROCm#1431]
As documentation of ROCm 4.1 release mentions Vega20 based devices seem to be temporarily disabled when upstream AMDGPU kernel module is used. As expected, after upgrading ROCm 4.0 to 4.1 `rocminfo` reports:

> HSA Error:  Incompatible kernel and userspace, Vega 20 [Radeon VII] disabled. Upgrade amdgpu.

(OpenSUSE Tumbleweed with kernel 5.11.6-1)

What version of kernel/amdgpu is required to re-enable Vega20 with ROCm 4.1?

**Comment by preda** [comment]
Please see #1423 for some context.

**Comment by FilipVaverka** [comment]
Thanks for the context. Is there bug report to follow on [https://gitlab.freedesktop.org/drm/amd](https://gitlab.freedesktop.org/drm/amd) or elsewhere?

**Comment by ROCmSupport** [comment]
Hi @FilipVaverka for reaching out.
Hope you got the context from #1423 
If yes, request you to close this ticket.
Thank you.

**Comment by ROCmSupport** [comment]
ROCm 4.0 and lower versions perfectly work with 5.10, 5.11 and 5.12 kernels.
ROCm 4.1 does not work on any of the Linux kernels 5.10, 5.11, 5.12. The error message "Upgrade amdgpu" as per the docs.
Fix will be available soon.

**Comment by FilipVaverka** [comment]
Well, I'm looking forward to the fix as ROCm 4.0.1 doesn't seem to work with 5.12.0 kernel anymore. Even simple "rocm-bandwidth-test" leads to display corruption and crash.

I get only repeated sequence of
> May 05 12:31:52 Filip kernel: amdgpu 0000:0d:00.0: amdgpu:          RW: 0x1
May 05 12:31:52 Filip kernel: amdgpu 0000:0d:00.0: amdgpu:          MAPPING_ERROR: 0x0
May 05 12:31:52 Filip kernel: amdgpu 0000:0d:00.0: amdgpu:          PERMISSION_FAULTS: 0x5
May 05 12:31:52 Filip kernel: amdgpu 0000:0d:00.0: amdgpu:          WALKER_ERROR: 0x0
May 05 12:31:52 Filip kernel: amdgpu 0000:0d:00.0: amdgpu:          MORE_FAULTS: 0x0
May 05 12:31:52 Filip kernel: amdgpu 0000:0d:00.0: amdgpu:          Faulty UTCL2 client ID: CPG (0x6)
May 05 12:31:52 Filip kernel: amdgpu 0000:0d:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x00040C50
May 05 12:31:52 Filip kernel: amdgpu 0000:0d:00.0: amdgpu:   in page starting at address 0x0000009e4000 from client 27
May 05 12:31:52 Filip kernel: amdgpu 0000:0d:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:40 vmid:0 pasid:0, for process  pid 0 thread  pid 0)

in system journal, which ends with

> May 05 12:31:57 Filip kernel: [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* Waiting for fences timed out!

**Comment by ROCmSupport** [comment]
We do not support ROCm 4.0.1 with the latest 5.12 kernels.
Request you to check the supported kernel section.
Thank you.

**Comment by FilipVaverka** [comment]
This is really confusing. I was unable to find any comprehensive list of compatible kernels when upstream amdgpu is used. Documentation mentions few supported Linux OS, where majority has kernels around 5.4, which is way too old (my assumption is this is the case for DKMS module distributed with ROCm).
On top of that your last message explicitly lists ROCm 4.0 and kernel 5.12 as compatible:

> ROCm 4.0 and lower versions perfectly work with 5.10, 5.11 and 5.12 kernels.
ROCm 4.1 does not work on any of the Linux kernels 5.10, 5.11, 5.12. The error message "Upgrade amdgpu" as per the docs.
Fix will be available soon.

**Comment by xuhuisheng** [comment]
Simply, ROCm-4.1 hadn't merged to upstream, so kernels-5.10, 11, 12 cannot use with ROCm-4.1 and Radeon VII.
ROCm-4.0 had merged to upstream, so kernel-5.10, 11, 12 can use with ROCm-4.0 and Radeon VII.

And ROCm-4.1 just meet a bug on supportting Radeon VII, which didn't merged to upstream, yet.
Maybe kernel-5.13 can merge ROCm-4.1 changes.

So Radeon VII + ROCm-4.0 + upstream kernel.
Or Radeon VII + ROCm-4.1 + rock-dkms-4.1(which based on kernel-5.9, not compatible with 5.10, 11, 12)

BTW, could we fix the issue on upstream by ourselves?

**Comment by FilipVaverka** [comment]
Thanks! So then, I must be hitting some other issue as I can't run even bandwidth test with ROCm 4.0.1 and 5.12.0 kernel (see above). It may have something to do with having both RX Vega 64 and Radeon VII in the machine.

**Comment by jedbrown** [comment]
ROCm-4.2 with Linux 5.10 (Debian) also fails. In the future, could you please put this information in the release notes?

> Fix will be available soon.

Could you share an ETA? Maybe this issue should stay open until a fix has been released?

**Comment by FilipVaverka** [comment]
Its buried deep down in [AMD ROCm™ Release Notes v4.2](https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html#driver-compability-issue-in-rocm-v4-1) as

> Driver Compability Issue in ROCm v4.1
>
> In certain scenarios, the ROCm v4.1 or higher run-time and userspace environment are not compatible with ROCm v4.0 and older driver implementations for 7nm-based (Vega 20) hardware (MI50 and MI60).
>
> To mitigate issues, the ROCm v4.1 or newer userspace prevents running older drivers for these GPUs.

Considering that the issue persists with ROCm 4.2 with kernel 5.12.0 it seems to me like there is no way to update "amdgpu" kernel module in upstream sooner than with 5.13 release in about two months. Having one of two officially supported architectures (considering only desktop products) disabled for so long with so little information doesn't seem very good for ROCm.

Only option seems to be to downgrade all the way to ROCm 4, but then there are other issues with that.
