### ISSUE TITLE
 Ubuntu 16.04.4 work arounds to install 

### ISSUE THREAD

**Issue by kevin** [RadeonOpenCompute/ROCm#362]
I tried Cent, then OpenSuSE ... because I'm not a huge fan of Ubuntu for technical reasons.

Anyway I've installed Ubuntu 16.04.4 and followed the instructions to the T on the ROCM installation page.  I can compile the HelloWorld, but it fails to find a working OpenCL runtime.

I've done nothing other than install Ubuntu 16.04.4 and then immediately follow the install instructions (this time).

HelloWorld fails with:
Failed to find any OpenCL platforms.
Failed to create OpenCL context.

... but compiles just fine obv.

clinfo fails with:
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)

Previously I've tried a mix of the amdgpu-pro installers, mesa, and pretty much everything under the sun.  I've had no problem getting mesa and the legacy stuff to work.  I've checked the ld.so.conf.d and it all looks okay by my eyes ... I've tried installing by hand from the Beta4.tar.gz ... I've tried installing from the local-repo ... I've tried installing from the network repo.amd site.

I'll write up changes to the documentation and push a merge on git ... if someone can help me get this running.  I feel like it's going to be something obvious I'm missing ... but i've hit a wall.

thx.

-k

**Comment by gstoner** [comment]
Did you add your user name to the Video group

**Comment by kevin** [comment]
Yup.

**Comment by gstoner** [comment]
Can you run HIP sample

**Comment by gstoner** [comment]
CENTOS/OPENSUSE are not supported

**Comment by kevin** [comment]
Oh I know ... I'm on Ubuntu 16.0.4.4 now ... and was trying to use the older releases on those machines.

**Comment by gstoner** [comment]
I was out on break last few day it is Spring Break in Austin.  I just saw Ubuntu just release. 16.04.4,  I have SQE running 16.04.4.  

If you run rocminfo what are the results

**Comment by kevin** [comment]
Okay ... so I just tried to build one of the samples in hip.

... and I got this:

Can't exec "/usr/local/cuda/bin/nvcc": No such file or directory at /opt/rocm/hip/bin/hipcc line 501.

I'm running a workstation with multiple cards in it (2 RX570 and 1 NVIDIA 1060) .... I have the monitor running through an nvidia card now, and previously was trying to make all of this work when running things through the onboard intel graphics since I always run headless and figured it would be better to run the monitor not on the cards.

Anyway.  I don't have cuda anything installed right now ... it's *just* ubuntu 16.04.4 and the stuff from the instructions page.

... but is this maybe because I'm running things through the Nvidia card?  Do I need to run my monitor through an AMD card for this to work?

Pulling the nvidia now ...

**Comment by kevin** [comment]
rocm info was giving me a nil result ... but I did just install mesa for shits and giggles to give myself a sanity check.

So it's throwing mesa info now:

=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (number of timestamp)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0                                  
  Queue Min Size:          0                                  
  Queue Max Size:          0                                  
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768KB                            
  Chip ID:                 0                                  
  Cacheline Size:          64                                 
  Max Clock Frequency (MHz):3900                               
  BDFID:                   0                                  
  Compute Unit:            4                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    4007116KB                          
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    4007116KB                          
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
  ISA Info:                
    N/A                      
*** Done ***

**Comment by gstoner** [comment]
The KFD driver has not started, the stack is not running based on this input.  Currently, you do have driver properly installed.

**Comment by kevin** [comment]
Okay ... trying to rebuild the DKMS modules by hand to see what's up.  I didn't see any errors on the install though and it seemed like everything built okay.

You think I would have better luck rolling back to 16.04?

I'll post if I can figure out any compile or load errors with the amdkfd module....

**Comment by kevin** [comment]
So rebuild the dkms modules amdkfd seems like it's loaded with lsmod:
root@noah-desktop:/opt/rocm/bin# lsmod | grep amd
amdkfd                188416  1
amd_iommu_v2           20480  1 amdkfd
amdgpu               2027520  4
i2c_algo_bit           16384  1 amdgpu
ttm                    94208  1 amdgpu
drm_kms_helper        167936  1 amdgpu
drm                   360448  6 amdgpu,ttm,drm_kms_helper

Also  ... and now I'm getting this result from rocminfo:

hsa api call failure at line 900, file: /rocmdata/jedwards/git/compute/rocrinfo/rocminfo.cc. Call returned 4104

**Comment by gstoner** [comment]
Yes we been running Ubuntu 16.04.3 with generic 4.13 kernel

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tekcomm** [comment]
This is because there is a problem with the 16.04.04, 16.04-03 works fine or also the latest nightly. 
The following has been tested and The KFC issue has been slated for official removal in the 4.17

http://kernel.ubuntu.com/~kernel-ppa/mainline/drm-intel-nightly/current/linux-headers-4.16.0-994_4.16.0-994.201803132200_all.deb
http://kernel.ubuntu.com/~kernel-ppa/mainline/drm-intel-nightly/current/linux-headers-4.16.0-994-lowlatency_4.16.0-994.201803132200_amd64.deb
http://kernel.ubuntu.com/~kernel-ppa/mainline/drm-intel-nightly/current/linux-image-4.16.0-994-lowlatency_4.16.0-994.201803132200_amd64.deb

#Testing on 16.04 with the beta drivers and its working fine.

or stock 
retpoline-4.16.0-994-lowlatency  System.map-4.16.0-994-lowlatency  vmlinuz-4.16.0-994-lowlatency
abi-4.16.0-994-lowlatency  config-4.16.0-994-lowlatency  grub  initrd.img-4.13.0-32-lowlatency.old-dkms  initrd.img-4.4.0-77-generic       System.map-4.13.0-32-lowlatency  vmlinuz-4.13.0-32-lowlatency
guru@AMD-rocm-rippa:~$ 

the .4.4 ubuntu is broken and I am not wasting my time backporting stuff.

**Comment by tekcomm** [comment]
apt-get remove intel-microcode#remove the broken microcode to fix the broken proccessors.#How to you know a update is really broken, when microsoft stops calling it a feature and starts calling it a rollback


#/etc/default/grub
The spectre of Sectre, causes issues and along nmi_watchdog like to byte on quite a few boards.
GRUB_CMDLINE_LINUX_DEFAULT="selinux=0 amdgpu.vm_fragment_size=9 nmi_watchdog=0 pti=off 3 spectre_v2=off nospectre_v2 nopti retp=0 ibrs=0 ibpb=0"

**Comment by wdormann** [comment]
FWIW, I ran into a similar problem.  But in my case, it was because I was booting with the "nomodeset" grub option, because without it I'd get a mostly-black, sometimes-flashing actual contents (once every couple seconds) display without it.

However, with "nomodeset", the GPU isn't recognized by the system / OpenCL.  As the result, I've removed the "nomodeset" boot option, and things are suddenly fine (aside from the flashing display).   In my case it's headless, so the flashing screen doesn't really matter to me.  But I suppose I'm curious how one can get both a non-flashing screen and a recognized GPU.

**Comment by kevin** [comment]
Thanks guys.  It seems like things are working with 16.04.03 just fine.

**Comment by tekcomm** [comment]
No prob, For headless I just delete the intel i915.ko and then
update-initramfs -u
Lazy fast quick :)

**Comment by tekcomm** [comment]
the 4.16 rc7 is out with the testing for the kfd :) Testing it right now on the polaris and vega
 git --git-dir=/dev/null clone --depth=1 https://github.com/M-Bab/linux-kernel-amdgpu-binaries

**Comment by rhlug** [comment]
@tekcomm can you get a working clinfo via amdgpu-pro or rocm with 4.16.0-rc7?  

I cannot.  The only working OCL I get with 4.16.0-rc7+  is Mesa 18. 

After installing amdgpu-pro 17.50, clinfo segfaults with amdgpu dkms loaded.  With amdgpu dkms unloaded,  I get "Number of platforms: 0" unless I enable the mesa.icd.

Also tried same with rocm.  dkms fails to load.  clinfo segfaults.

```
ERROR (dkms apport): kernel package linux-headers-4.16.0-rc7+ is not supported
```

Without dkms loaded, "Number of platforms: 0"

Back to mesa 18.

```
# clinfo
Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 18.1.0-devel
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Clover
Number of devices                                 6
  Device Name                                     Radeon RX Vega (VEGA10 / DRM 3.25.0 / 4.16.0-rc7+, LLVM 6.0.0)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa 18.1.0-devel
```

**Comment by rhlug** [comment]
amdgpu dkms not supported either i guess.

```
# dkms install amdgpu/17.50-511655 

Creating symlink /var/lib/dkms/amdgpu/17.50-511655/source ->
                 /usr/src/amdgpu-17.50-511655

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Running the pre_build script:

Building module:
cleaning build area....
make KERNELRELEASE=4.16.0-rc7+ -j4 -C /lib/modules/4.16.0-rc7+/build M=/var/lib/dkms/amdgpu/17.50-511655/build....(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-4.16.0-rc7+ is not supported
Error! Bad return status for module build on kernel: 4.16.0-rc7+ (x86_64)
Consult /var/lib/dkms/amdgpu/17.50-511655/build/make.log for more information.
```

**Comment by tekcomm** [comment]
IIt wont work on that one the 4.15 it works and the 4.16 drm

**Comment by rhlug** [comment]
But vega pp_table wasnt fixed until march 26 nightly.  Didnt work in 994, worked in 996.  So thats a deal breaker.  I shall wait longer...

**Comment by tekcomm** [comment]
I am waiting on a donation of a vega, You should be able to use amdgpupro
and install the legacy opencl drivers and use those. I had the nightly
running the opencl 2.2 btw

**Comment by tekcomm** [comment]
Dkms does work on the git pull from the article I posted. It has the 4.17
patches here
https://lists.freedesktop.org/archives/dri-devel/2018-March/170894.html

**Comment by rhlug** [comment]
the latest m-bab?  thats what one i installed.  thats what produced the error above

specifically...
```
# dkms install amdgpu/17.50-511655 
ERROR (dkms apport): kernel package linux-headers-4.16.0-rc7+ is not supported
```

**Comment by tekcomm** [comment]
Ill have a vega next week and build and test a git pull from the latest one
thats going into the 4.17

**Comment by tekcomm** [comment]
The mbab does not include th patches from

 Merge branch 'drm-next-4.17' of
git://people.freedesktop.org/~agd5f/linux into drm-next (2018-03-26
10:01:11 +1000)

are available in the Git repository at:

  git://people.freedesktop.org/~gabbayo/linux tags/drm-amdkfd-next-2018-03-27

for you to fetch changes up to 1679ae8f8f4148766423066aeb3dbb0a985a373a:

  drm/amdkfd: Use ordered workqueue to restore processes (2018-03-23
15:30:36 -0400)

----------------------------------------------------------------
Arnd Bergmann (1):
      drm/amdkfd: fix uninitialized variable use

Felix Kuehling (15):
      drm/amdgpu: Move KFD-specific fields into struct amdgpu_vm
      drm/amdgpu: Fix initial validation of PD BO for KFD VMs
      drm/amdgpu: Add helper to turn an existing VM into a compute VM
      drm/amdgpu: Add kfd2kgd interface to acquire an existing VM
      drm/amdkfd: Create KFD VMs on demand
      drm/amdkfd: Remove limit on number of GPUs
      drm/amdkfd: Aperture setup for dGPUs
      drm/amdkfd: Add per-process IDR for buffer handles
      drm/amdkfd: Allocate CWSR trap handler memory for dGPUs
      drm/amdkfd: Add TC flush on VMID deallocation for Hawaii
      drm/amdkfd: Add ioctls for GPUVM memory management
      drm/amdkfd: Kmap event page for dGPUs
      drm/amdkfd: Add module option for testing large-BAR functionality
      drm/amdgpu: Fix acquiring VM on large-BAR systems
      drm/amdkfd: Use ordered workqueue to restore processes

Oak Zeng (1):
      drm/amdkfd: Populate DRM render device minor

Oded Gabbay (1):
      drm/amdkfd: add missing include of mm.h

 drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd.h         |  28 +-
 drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gfx_v7.c  |   1 +
 drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gfx_v8.c  |   1 +
 drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd_gpuvm.c   | 249 ++++++----
 drivers/gpu/drm/amd/amdgpu/amdgpu_vm.c             |  73 ++-
 drivers/gpu/drm/amd/amdgpu/amdgpu_vm.h             |  10 +
 drivers/gpu/drm/amd/amdkfd/kfd_chardev.c           | 532 +++++++++++++++++++++
 drivers/gpu/drm/amd/amdkfd/kfd_crat.c              |   5 +-
 .../gpu/drm/amd/amdkfd/kfd_device_queue_manager.c  |  22 +-
 drivers/gpu/drm/amd/amdkfd/kfd_events.c            |  31 +-
 drivers/gpu/drm/amd/amdkfd/kfd_flat_memory.c       |  59 ++-
 drivers/gpu/drm/amd/amdkfd/kfd_module.c            |  11 +-
 drivers/gpu/drm/amd/amdkfd/kfd_packet_manager.c    |  37 ++
 drivers/gpu/drm/amd/amdkfd/kfd_priv.h              |  39 +-
 drivers/gpu/drm/amd/amdkfd/kfd_process.c           | 334 ++++++++++++-
 drivers/gpu/drm/amd/amdkfd/kfd_topology.c          |   4 +
 drivers/gpu/drm/amd/amdkfd/kfd_topology.h          |   1 +
 drivers/gpu/drm/amd/include/kgd_kfd_interface.h    |   4 +
 include/uapi/linux/kfd_ioctl.h                     | 122 ++++-
 19 files changed, 1398 insertions(+), 165 deletions(-)


The drm next is getting tested tonight with those patches

**Comment by tekcomm** [comment]
root@AMD-rocm-rippa:/home/guru# dmesg | grep amd
[    1.105708] [drm] amdgpu kernel modesetting enabled.
[    1.125128] fb: switching to amdgpudrmfb from EFI VGA
[    1.127266] amdgpu 0000:01:00.0: Invalid PCI ROM header signature:
expecting 0xaa55, got 0xffff
[    1.127338] amdgpu 0000:01:00.0: BAR 2: releasing [mem
0xe0000000-0xe01fffff 64bit pref]
[    1.127341] amdgpu 0000:01:00.0: BAR 0: releasing [mem
0xd0000000-0xdfffffff 64bit pref]
[    1.127363] amdgpu 0000:01:00.0: BAR 0: assigned [mem
0x2000000000-0x21ffffffff 64bit pref]
[    1.127370] amdgpu 0000:01:00.0: BAR 2: assigned [mem
0x2200000000-0x22001fffff 64bit pref]
[    1.127394] amdgpu 0000:01:00.0: VRAM: 8192M 0x000000F400000000 -
0x000000F5FFFFFFFF (8192M used)
[    1.127396] amdgpu 0000:01:00.0: GTT: 256M 0x0000000000000000 -
0x000000000FFFFFFF
[    1.127445] [drm] amdgpu: 8192M of VRAM memory ready
[    1.127447] [drm] amdgpu: 8192M of GTT memory ready.
[    1.865562] [drm] Initialized amdgpu 3.23.0 20150101 for 0000:01:00.0 on
minor 0
[    1.865596] amdgpu 0000:05:00.0: enabling device (0000 -> 0003)
[    2.940308] amdgpu 0000:05:00.0: BAR 2: releasing [mem
0x2ff0000000-0x2ff01fffff 64bit pref]
[    2.940311] amdgpu 0000:05:00.0: BAR 0: releasing [mem
0x2fe0000000-0x2fefffffff 64bit pref]
[    2.940347] amdgpu 0000:05:00.0: BAR 0: assigned [mem
0x2400000000-0x25ffffffff 64bit pref]
[    2.940358] amdgpu 0000:05:00.0: BAR 2: assigned [mem
0x2300000000-0x23001fffff 64bit pref]
[    2.940392] amdgpu 0000:05:00.0: VRAM: 8192M 0x000000F400000000 -
0x000000F5FFFFFFFF (8192M used)
[    2.940394] amdgpu 0000:05:00.0: GTT: 256M 0x0000000000000000 -
0x000000000FFFFFFF
[    2.940406] [drm] amdgpu: 8192M of VRAM memory ready
[    2.940408] [drm] amdgpu: 8192M of GTT memory ready.
[    3.658624] [drm] Initialized amdgpu 3.23.0 20150101 for 0000:05:00.0 on
minor 1
root@AMD-rocm-rippa:/home/guru# cl
clear          clear_console  clinfo
root@AMD-rocm-rippa:/home/guru# cl
clear          clear_console  clinfo
root@AMD-rocm-rippa:/home/guru# clinfo
Number of platforms: 1
  Platform Profile: FULL_PROFILE
  Platform Version: OpenCL 2.1 AMD-APP (2527.3)
  Platform Name: AMD Accelerated Parallel Processing
  Platform Vendor: Advanced Micro Devices, Inc.
  Platform Extensions: cl_khr_icd cl_amd_event_callback
cl_amd_offline_devices


  Platform Name: AMD Accelerated Parallel Processing
Number of devices: 2
  Device Type: CL_DEVICE_TYPE_GPU
  Vendor ID: 1002h
  Board name: Radeon RX 570 Series
  Device Topology: PCI[ B#1, D#0, F#0 ]
  Max compute units: 32
  Max work items dimensions: 3
    Max work items[0]: 1024
    Max work items[1]: 1024
    Max work items[2]: 1024
  Max work group size: 256
  Preferred vector width char: 4
  Preferred vector width short: 2
  Preferred vector width int: 1
  Preferred vector width long: 1
  Preferred vector width float: 1
  Preferred vector width double: 1
  Native vector width char: 4
  Native vector width short: 2
  Native vector width int: 1
  Native vector width long: 1
  Native vector width float: 1
  Native vector width double: 1
  Max clock frequency: 1150Mhz
  Address bits: 64
  Max memory allocation: 4244635648
  Image support: Yes
  Max number of images read arguments: 128
  Max number of images write arguments: 8
  Max image 2D width: 16384
  Max image 2D height: 16384
  Max image 3D width: 2048
  Max image 3D height: 2048
  Max image 3D depth: 2048
  Max samplers within kernel: 16
  Max size of kernel argument: 1024
  Alignment (bits) of base address: 2048
  Minimum alignment (bytes) for any datatype: 128
  Single precision floating point capability
    Denorms: No
    Quiet NaNs: Yes
    Round to nearest even: Yes
    Round to zero: Yes
    Round to +ve and infinity: Yes
    IEEE754-2008 fused multiply-add: Yes
  Cache type: Read/Write
  Cache line size: 64
  Cache size: 16384
  Global memory size: 5746974720
  Constant buffer size: 4244635648
  Max number of constant args: 8
  Local memory type: Scratchpad
  Local memory size: 32768
  Max pipe arguments: 0
  Max pipe active reservations: 0
  Max pipe packet size: 0
  Max global variable size: 0
  Max global variable preferred total size: 0
  Max read/write image args: 0
  Max on device events: 0
  Queue on device max size: 0
  Max on device queues: 0
  Queue on device preferred size: 0
  SVM capabilities:
    Coarse grain buffer: No
    Fine grain buffer: No
    Fine grain system: No
    Atomics: No
  Preferred platform atomic alignment: 0
  Preferred global atomic alignment: 0
  Preferred local atomic alignment: 0
  Kernel Preferred work group size multiple: 64
  Error correction support: 0
  Unified memory for Host and Device: 0
  Profiling timer resolution: 1
  Device endianess: Little
  Available: Yes
  Compiler available: Yes
  Execution capabilities:
    Execute OpenCL kernels: Yes
    Execute native function: No
  Queue on Host properties:
    Out-of-Order: No
    Profiling : Yes
  Queue on Device properties:
    Out-of-Order: No
    Profiling : No
  Platform ID: 0x7f3d43c0d510
  Name: Ellesmere
  Vendor: Advanced Micro Devices, Inc.
  Device OpenCL C version: OpenCL C 1.2
  Driver version: 2527.3
  Profile: FULL_PROFILE
  Version: OpenCL 1.2 AMD-APP (2527.3)
  Extensions: cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics
cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics
cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics
cl_khr_int64_extended_atomics cl_khr_3d_image_writes
cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing
cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops
cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir
cl_khr_gl_event


  Device Type: CL_DEVICE_TYPE_GPU
  Vendor ID: 1002h
  Board name: Radeon RX 570 Series
  Device Topology: PCI[ B#5, D#0, F#0 ]
  Max compute units: 32
  Max work items dimensions: 3
    Max work items[0]: 1024
    Max work items[1]: 1024
    Max work items[2]: 1024
  Max work group size: 256
  Preferred vector width char: 4
  Preferred vector width short: 2
  Preferred vector width int: 1
  Preferred vector width long: 1
  Preferred vector width float: 1
  Preferred vector width double: 1
  Native vector width char: 4
  Native vector width short: 2
  Native vector width int: 1
  Native vector width long: 1
  Native vector width float: 1
  Native vector width double: 1
  Max clock frequency: 1150Mhz
  Address bits: 64
  Max memory allocation: 4244635648
  Image support: Yes
  Max number of images read arguments: 128
  Max number of images write arguments: 8
  Max image 2D width: 16384
  Max image 2D height: 16384
  Max image 3D width: 2048
  Max image 3D height: 2048
  Max image 3D depth: 2048
  Max samplers within kernel: 16
  Max size of kernel argument: 1024
  Alignment (bits) of base address: 2048
  Minimum alignment (bytes) for any datatype: 128
  Single precision floating point capability
    Denorms: No
    Quiet NaNs: Yes
    Round to nearest even: Yes
    Round to zero: Yes
    Round to +ve and infinity: Yes
    IEEE754-2008 fused multiply-add: Yes
  Cache type: Read/Write
  Cache line size: 64
  Cache size: 16384
  Global memory size: 5746974720
  Constant buffer size: 4244635648
  Max number of constant args: 8
  Local memory type: Scratchpad
  Local memory size: 32768
  Max pipe arguments: 0
  Max pipe active reservations: 0
  Max pipe packet size: 0
  Max global variable size: 0
  Max global variable preferred total size: 0
  Max read/write image args: 0
  Max on device events: 0
  Queue on device max size: 0
  Max on device queues: 0
  Queue on device preferred size: 0
  SVM capabilities:
    Coarse grain buffer: No
    Fine grain buffer: No
    Fine grain system: No
    Atomics: No
  Preferred platform atomic alignment: 0
  Preferred global atomic alignment: 0
  Preferred local atomic alignment: 0
  Kernel Preferred work group size multiple: 64
  Error correction support: 0
  Unified memory for Host and Device: 0
  Profiling timer resolution: 1
  Device endianess: Little
  Available: Yes
  Compiler available: Yes
  Execution capabilities:
    Execute OpenCL kernels: Yes
    Execute native function: No
  Queue on Host properties:
    Out-of-Order: No
    Profiling : Yes
  Queue on Device properties:
    Out-of-Order: No
    Profiling : No
  Platform ID: 0x7f3d43c0d510
  Name: Ellesmere
  Vendor: Advanced Micro Devices, Inc.
  Device OpenCL C version: OpenCL C 1.2
  Driver version: 2527.3
  Profile: FULL_PROFILE
  Version: OpenCL 1.2 AMD-APP (2527.3)
  Extensions: cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics
cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics
cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics
cl_khr_int64_extended_atomics cl_khr_3d_image_writes
cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing
cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops
cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir
cl_khr_gl_event


root@AMD-rocm-rippa:/home/guru# uname -a
Linux AMD-rocm-rippa 4.16.0-041600rc7-generic #201803252030 SMP Mon Mar 26
00:32:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@AMD-rocm-rippa:/home/guru# cd
root@AMD-rocm-rippa:~# ls
amdcovc     amdtweak-master  Claymore  fah       HelloWorld
 installnvidiasupport.sh  nohup.out          QuantumRNG  sgminer
 start-oc.sh       start-rtminer.sh
amdgpu-pro  atiflash         ethminer  fahtmpfs  HelloWorld.cl
installvegasupport.sh    PolarisBiosEditor  r8168       start-net.sh
start-rtlinux.sh  start.sh
root@AMD-rocm-rippa:~# cd /home
root@AMD-rocm-rippa:/home# cd guru/
root@AMD-rocm-rippa:/home/guru# ls
add2bashrc         linux-headers-4.16.0-041600rc
7_4.16.0-041600rc7.201803252030_all.deb            text-mode-fonts
clean-myself.bash  linux-headers-4.16.0-041600rc7
-generic_4.16.0-041600rc7.201803252030_amd64.deb  text-mode-installer
fontlist           linux-image-4.16.0-041600rc7-
generic_4.16.0-041600rc7.201803252030_amd64.deb    text-mode-menu
l                  r8168-dkms_8.045.08-2_all.deb
                       truncate-log

Attached is the kernel version to try
​
 linux-headers-4.16.0-041600rc7-generic_4.16.0-0...
<https://drive.google.com/file/d/1hdaPRU02W8GLP5e1ib35Fzb-FXtX5w9t/view?usp=drive_web>
​​
 linux-headers-4.16.0-041600rc7_4.16.0-041600rc7...
<https://drive.google.com/file/d/1qKAcyZx52z8c1MfeZz-gIX7JxSacFemv/view?usp=drive_web>
​​
 linux-image-4.16.0-041600rc7-generic_4.16.0-041...
<https://drive.google.com/file/d/1bstQ1wHZYDRh3Xszt3P7KuwmJ22jsBbb/view?usp=drive_web>
​​
 r8168-dkms_8.045.08-2_all.deb
<https://drive.google.com/file/d/17hQJu6EpTaJpoqGAK2artxx3Ie7NA7O-/view?usp=drive_web>
​

**Comment by rhlug** [comment]
what does your dkms look like on 4.16.0-041600rc7-generic 

```
# dkms status
```

i built kernels from amd-staging-drm-next and drm-next-4.17-wip repos and i have no working vegas.    Both of them end up with this error, and clinfo hangs indefinitely

```
Mar 30 08:31:43 rig23 kernel: [   38.368042] [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring sdma0 timeout, last signaled seq=3, last emitted seq=5
Mar 30 08:31:43 rig23 kernel: [   38.368365] [drm] No hardware hang detected. Did some blocks stall?
```

If I revert to 4.16.0-996-lowlatency, my vegas all work.   Not sure whats going on there, maybe some regression.

**Comment by tekcomm** [comment]
THANK YOU, I am going to let the guys know asap.

**Comment by tekcomm** [comment]
sdma0 timeouts are something else. You need to late init the driver.

**Comment by tekcomm** [comment]
Please hit me on gmail chat  I have a need some more info.

**Comment by tekcomm** [comment]
Ya ran into that and I fixed it on the live dev system it will pop up again
some systems get it. On the kernels it has to do with when the cards are
init vga=0 I got around it by blacklisting the init the cards. I'm getting
all st 80mhs on two RX 570 with I'll grab the source and check it out l8r
when my I get a Vega

**Comment by rhlug** [comment]
I'll give it a shot.  Its funny that 4 GPU would come up, but my ethminer wasnt crunching any hashes.  It thought it was, but was reporting 0.0 Mh/s.      Back on  4.16.0-996-lowlatency and I'm crunching ~230Mh/s on 6x vega.

drm-next-4.17-wip and Mesa 18.1 must not be a good combo.

**Comment by tekcomm** [comment]
What model is your ethernet and can you please send me a full dmesg....
Here is the new interface Im working on for The RIppa. For beaver verson
since its headless. It gets rid of all the display crap and uses a single
pipe, Gpu failure and autorestart ever hour since it boots in 8 seconds.

**Comment by tekcomm** [comment]
https://cgit.freedesktop.org/~agd5f/linux/log/?h=amd-staging-drm-next

The sdma hang fix has been submitted btw

**Comment by rhlug** [comment]
I can confirm, the smda0 ring error is gone on amd-staging-drm-next.  All 6 of my vegas come up, and I get a proper environment with mesa/clover. 

However, I'm unable to get a working clinfo on that kernel with amdgpu or amdgpu-pro.   Tried to reinstall amdgpu-pro-17.50, and still get errors on dkms module.

```
Building initial module for 4.16.0-amd-staging-180401
ERROR (dkms apport): kernel package linux-headers-4.16.0-amd-staging-180401 is not supported
Error! Bad return status for module build on kernel: 4.16.0-amd-staging-180401 (x86_64)
Consult /var/lib/dkms/amdgpu/17.50-511655/build/make.log for more information.
```

**Comment by rhlug** [comment]
drm-tip 4.16.0-994-lowlatency 20180404 works.

**Comment by tekcomm** [comment]
Linux AMD-rocm-rippa 4.16.0-996-lowlatency #201803252200
linux-image-4.16.0-996-lowlatency_4.16.0-996.201803252200_amd64.deb
Pushing 40.5Mhs on 570's while folding at the same time

**Comment by tekcomm** [comment]
​Dualmining on two 570's I am just about to get a solid 80Mhs

**Comment by tekcomm** [comment]
4.17-rc1 failed on mine

**Comment by tekcomm** [comment]
Tag your it, please report #gpus and the kerenl that did not explode with
dark fobodings too. latest babs ring timeouts 4.16.12

**Comment by rhlug** [comment]
I have been running  fkxamd/drm-next-wip tag (4.17.0-rc2-180424-fkxamd) as recommended by Felix.   It gave me functional power play on all 6 vegas under Mesa opencl.  I havent been running ROCm lately because I couldnt get any dkms loading on any recent kernel that had functional pp_table, and that was a deal break in term of power consumption.

**Comment by tekcomm** [comment]
Shit that means tag im it.

**Comment by tekcomm** [comment]
We hope you enjoy your new vega now here are a few pointers on what may
happen
https://youtu.be/zAVcYYTVJTY?t=34

**Comment by tekcomm** [comment]
and the thread marches on to the next day and kernel update down date
sometime around date

**Comment by rhlug** [comment]
Yes, my "new vegas" bought 8 months ago.   We'll have a working linux environment for vega10 just in time for the vega20 drop.  :-)

**Comment by tekcomm** [comment]
Wow so I just have to look for the missing vega30 firmware to know the 20's
dropped
